// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3UZoF5nujrpGrcRWI_SkRSxfgmuBaGuo',
    appId: '1:870628664042:web:22e9e82c0f0e57cad6ad93',
    messagingSenderId: '870628664042',
    projectId: 'prakmb-e7a17',
    authDomain: 'prakmb-e7a17.firebaseapp.com',
    storageBucket: 'prakmb-e7a17.firebasestorage.app',
    measurementId: 'G-SZJKXF8LLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD69lJKAMFzZJpDbe6OhOXVp-2KZfcjfmA',
    appId: '1:870628664042:android:922e43dd0af5002cd6ad93',
    messagingSenderId: '870628664042',
    projectId: 'prakmb-e7a17',
    storageBucket: 'prakmb-e7a17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa3s0Tqmny7o01IvWFQ9YByy-Qr2hK6q0',
    appId: '1:870628664042:ios:e8fe645ccbf0d5d0d6ad93',
    messagingSenderId: '870628664042',
    projectId: 'prakmb-e7a17',
    storageBucket: 'prakmb-e7a17.firebasestorage.app',
    iosBundleId: 'com.example.prakmb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa3s0Tqmny7o01IvWFQ9YByy-Qr2hK6q0',
    appId: '1:870628664042:ios:e8fe645ccbf0d5d0d6ad93',
    messagingSenderId: '870628664042',
    projectId: 'prakmb-e7a17',
    storageBucket: 'prakmb-e7a17.firebasestorage.app',
    iosBundleId: 'com.example.prakmb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3UZoF5nujrpGrcRWI_SkRSxfgmuBaGuo',
    appId: '1:870628664042:web:2c57140e1d6f7cc5d6ad93',
    messagingSenderId: '870628664042',
    projectId: 'prakmb-e7a17',
    authDomain: 'prakmb-e7a17.firebaseapp.com',
    storageBucket: 'prakmb-e7a17.firebasestorage.app',
    measurementId: 'G-NHSXQ5WT9K',
  );

}